# Generated by Django 6.0.6 on 2026-06-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='occurrence_count',
            field=models.IntegerField(default=1),
        ),
    ]
