# Generated by Django 6.0.6 on 2026-06-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
